config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :participantes
  resources :home, only: [:index]

  match '/admin/participantes' => 'home#index', via: [:get, :post]
  match '/admin/grupos' => 'home#index2', via: [:get, :post]

  root :to => 'grupos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grupo.rb
class Grupo < ApplicationRecord

	has_attached_file :image
	has_many :participantes

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates_presence_of :nome

	def verificaParticipantes(grupo)
		if grupo.participantes.size == 5
			grupo.status = true
			grupo.participantes.each do |g|
				if g.status != true
					grupo.status = false
				end
			end
		end
	end
end

app/models/home.rb
class Home < ApplicationRecord
	paginates_per 10
end

app/models/participante.rb
class Participante < ApplicationRecord
	belongs_to :grupo
	validates_presence_of :nome, :matricula
	paginates_per 5

	def self.search(query)
		if (query.present?)
			find_by(['matricula LIKE :query', query: "#{query}"])
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :verificaParticipantes
	
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]
  
  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all.order(:status)

    @grupos.each do |f|
        f.verificaParticipantes(f)
    end
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    @grupo = set_grupo
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)
    @grupo.status = false
    
    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'Grupo was successfully created.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:nome, :status, :image, :other)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@participantes = Participante.all
	end

	def index2
		@grupos = Grupo.all
	end


end

app/controllers/participantes_controller.rb
class ParticipantesController < ApplicationController
  before_action :set_participante, only: [:show, :edit, :update, :destroy]

  # GET /participantes
  # GET /participantes.json
  def index
    @participantes = Participante.all.page params[:page]
  end

  # GET /participantes/1
  # GET /participantes/1.json
  def show
  end

  # GET /participantes/new
  def new
    @participante = Participante.new
  end

  # GET /participantes/1/edit
  def edit
  end

  # POST /participantes
  # POST /participantes.json
  def create
    @participante = Participante.new(participante_params)

    respond_to do |format|
      if @participante.save
        format.html { redirect_to @participante, notice: 'Participante was successfully created.' }
        format.json { render :show, status: :created, location: @participante }
      else
        format.html { render :new }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participantes/1
  # PATCH/PUT /participantes/1.json
  def update
    respond_to do |format|
      if @participante.update(participante_params)
        format.html { redirect_to @participante, notice: 'Participante was successfully updated.' }
        format.json { render :show, status: :ok, location: @participante }
      else
        format.html { render :edit }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participantes/1
  # DELETE /participantes/1.json
  def destroy
    @participante.destroy
    respond_to do |format|
      format.html { redirect_to participantes_url, notice: 'Participante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participante  
      @participante = Participante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participante_params
      params.require(:participante).permit(:nome, :matricula, :status, :grupo_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/participantes_helper.rb
module ParticipantesHelper
end

app/views/grupos/_form.html.erb
<%= form_with(model: grupo, local: true) do |form| %>
  <% if grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :grupo_nome %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<div class="container">
  <h1>Grupos</h1>
  <table>
    <thead>
      <tr>
      <th>Icone</th>
        <th>Time</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @grupos.each do |grupo| %>
      <tr>
        <td><%= image_tag(grupo.image, class: 'circle icon_grupo')%></td>
        <td><%= grupo.nome %></td>
        <td><%= grupo.status %></td>
        <td><%= link_to 'Mostrar', grupo %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>
      <%= link_to 'Novo Grupo', new_grupo_path, class: 'btn #ffffff white' %>

      <br><br><br>
</div>

app/views/grupos/new.html.erb
<div class="container">
  <h1>Criar Grupo</h1>
  <%= render 'form', grupo: @grupo %>
</div>

app/views/grupos/show.html.erb
<div class="container">
	<h1>Participantes do Grupo</h1>
	<table class="stripped">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Matricula</th>
				<th>Status</th>
			</tr>
		</thead>
		<% @grupo.participantes.each do |p| %>
		<tbody>
			<tr>
				<td><%= p.nome %></td>
				<td><%= p.matricula %></td>

				<% if p.status == false %>
				<td> Não Confirmado </td>
				<% else %>
				<td> Confirmado  </td>
				<% end %>
			</tr>
		</tbody>
		<% end %>
	</table>

	<br>
	<br>

	<%= link_to 'Voltar', grupos_path,class: 'btn #424242 grey darken-3' %>

	<br>
	<br>
</div>

app/views/home/index.html.erb
<div class="container">
<h1 style="text-align: center;">Participantes</h1>
<table class="centered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Confirmado</th>
      <th>Equipe</th>
      <th>Icone</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <tbody>
    <% @participantes.each do |participante| %>
      <tr>
        <td><%= participante.nome %></td>
        <td><%= participante.matricula %></td>
        <% if (participante.status == true) %>
              <td><i class="material-icons">check</i></td>
        <% else %>
              <td><i class="material-icons">clear</i></td>
        <% end %>
        <td><%= participante.grupo.nome %> </td>
        <td><%= image_tag(participante.grupo.image, class: 'circle icon_grupo') %></td>
        <td><%= link_to 'Mostrar', participante %></td>
        <td><%= link_to 'Editar', edit_participante_path(participante) %></td>
        <td><%= link_to 'Excluir', participante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Participante', new_participante_path, class: 'btn #424242 grey darken-3' %>

</div>
<br>

app/views/home/index2.html.erb
<div class="container">
  <h1 style="text-align: center;">Grupos</h1>
  <table class="centered">
    <thead>
      <tr>
      <th>Icone</th>
        <th>Time</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @grupos.each do |grupo| %>
      <tr>
        <td><%= image_tag(grupo.image, class: 'circle icon_grupo')%></td>
        <td><%= grupo.nome %></td>
          
        <% if (grupo.status == true) %>
              <td><i class="material-icons">check</i></td>
        <% else %>
              <td><i class="material-icons">clear</i></td>
        <% end %>
        <td><%= link_to 'Mostrar', grupo %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>
      <%= link_to 'Novo Grupo', new_grupo_path, class: 'btn #424242 grey darken-3' %>

      <br><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<head>
		<title>Campeonato</title>
		<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
		<!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous"-->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
			<!-- Compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

		<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	 	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav>
    <div class="nav-wrapper">
    	<%= image_tag('logo_unilol-e3ab34bbe7881999259faa14be7e9099.png', class: 'brand-logo right') %>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to 'Equipes', grupos_path %></li>
        <li><%= link_to 'Participantes', participantes_path %></li>
      </ul>
    </div>
  </nav>
		<%= yield %>
	</body>

	<footer>
	        <p>© Desenvolvido pelo NExTI - Núcleo de Extensão em Sistemas de Informação.</p>
	</footer>

app/views/participantes/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('select').material_select();
  });
</script>

<%= form_with(model: participante, local: true) do |form| %>
  <% if participante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participante.errors.count, "error") %> prohibited this participante from being saved:</h2>

      <ul>
      <% participante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :participante_nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.number_field :matricula, id: :participante_matricula %>
  </div>

  <div class="field">
    <%= form.check_box :status, id: :participante_status %>
    <%= form.label :status %>
  </div>

  <div>
    <br>
    <label>Escolha o Time</label>
       <%= form.collection_select :grupo_id, Grupo.order(:nome), :id, :nome, class: "browser-default"%>
  </div>

  <div>
    <br>
    <%= form.submit 'Confirmar', class: 'btn #757575 grey darken-1' %>
  </div>

<% end %>

app/views/participantes/edit.html.erb
<div class="container">
	<h1>Editar Participante</h1>
	<%= render 'form', participante: @participante %>
	<br>
	<%= link_to 'Mostrar', @participante, class: 'btn 424242 grey darken-3'%>
	<%= link_to 'Voltar', participantes_path, class: 'btn 424242 grey darken-3' %>
	<br> 
	<br>
	<br>
</div>

app/views/participantes/index.html.erb
<div class="container">
<h1 style="color: dimgrey; text-align: center;">Participantes</h1>
<table class="centered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Confirmado</th>
      <th>Equipe</th>
      <th>Icone</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <tbody>
    <% @participantes.each do |participante| %>
      <tr>
        <td><%= participante.nome %></td>
        <td><%= participante.matricula %></td>
        <% if (participante.status == true) %>
              <td><i class="material-icons">check</i></td>
        <% else %>
              <td><i class="material-icons">clear</i></td>
        <% end %>
        <td><%= participante.grupo.nome %> </td>
        <td><%= image_tag(participante.grupo.image, class: 'circle icon_grupo') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to_next_page @participantes, 'Próxima página', class: 'btn #424242 grey darken-3' %>
<%= link_to_prev_page @participantes, 'Página anterior', class: 'btn #424242 grey darken-3' %>
<br>
<br>

</div>

app/views/participantes/new.html.erb
<div class="container">

	<h1>Criar Participante</h1>
		<%= render 'form', participante: @participante %>
	<br>
	<%= link_to 'Voltar', home_index_path, class: 'btn #424242 grey darken-3' %>

</div>

<br>

app/views/participantes/show.html.erb
<div class="container">
  <h2>Informações</h2>
    <table class="stripped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Matricula</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @participante.nome %></td>
        <td><%= @participante.matricula %></td>
        <% if (@participante.status == true) %>
              <td><i class="material-icons">check</i></td>
        <% else %>
              <td><i class="material-icons">clear</i></td>
        <% end %>
      </tr>
      </tbody>
    </table>
<%= link_to 'Edit', edit_participante_path(@participante) %> |
<%= link_to 'Back', participantes_path %>
</div>